### ISSUE TITLE
kobo-transfer using EU servers

### ISSUE THREAD

**Issue by rkopper-wv** [kobotoolbox/kobo-transfer#41]
I have posted this question on the community forum but posting here for visibility:
https://community.kobotoolbox.org/t/moving-submission-to-another-form/52804/6?u=rkopper_wv

Does this script work for the eu severs? My account is on the EU URL. From my understanding I would change the config json file to have:
“kc_url”: https://eu.kobotoolbox.org/" (and the same for kf_url*)
rather than
“kc_url”: ''https://kf.kobotoolbox.org/"

When I try to run this, I get error-- Invalid kc_url for src.

when I change the url back to kf I receive error – Invalid token for src.

I - thanks

**Comment by joshuaberetta** [comment]
Hi @rkopper-wv, I will respond in the forum and close this issue.
